services:

  db:
    image: mariadb:11
    restart: always
    volumes:
      - ./wp_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: /run/secrets/db_name
      MYSQL_USER: /run/secrets/wp_user
      MYSQL_PASSWORD: /run/secrets/db_password

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: /run/secrets/wp_user
      PMA_PASSWORD: /run/secrets/db_password
    ports:
      - "8080:80"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: /run/secrets/wp_user
      WORDPRESS_DB_PASSWORD: /run/secrets/db_password
      WORDPRESS_DB_NAME: /run/secrets/db_name
    volumes:
      - ./wp_content:/var/www/html

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_name:
    file: ./secrets/db_name.txt
  wp_user:
    file: ./secrets/wp_user.txt
