services:

  db:
    image: mariadb:11
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    env_file:
      - ./.env
    restart: always
    environment:
      PMA_HOST: db:3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    ports:
      - "8080:80"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    env_file:
      - ./.env
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./site:/var/www/html

#secrets:
#  db_password:
#    file: ./secrets/db_password.txt
#  db_root_password:
#    file: ./secrets/db_root_password.txt
#  db_name:
#    file: ./secrets/db_name.txt
#  wp_user:
#    file: ./secrets/wp_user.txt
